#define IDH_OBJECT_Notes 100
#define IDH_DISPATCH_Notes 101
#define IDH_METHOD_Notes_CollapseAll 102
#define IDH_METHOD_Notes_ShowAll 103
#define IDH_METHOD_Notes_HideAll 104
#define IDH_METHOD_Notes_AddNote 105
#define IDH_METHOD_Notes_DeleteNote 106
#define IDH_PROPERTY_Notes_Notes 107
#define IDH_METHOD_Notes_SaveAll 108
#define IDH_METHOD_Notes_SetOnTop 109
#define IDH_METHOD_Notes_LoadAll 110
#define IDH_PROPERTY_Notes_IsChanged 111
#define IDH_PROPERTY_Notes_ThroughClicks 112
#define IDH_PROPERTY_Notes_TransparencyLevel 113
#define IDH_OBJECT_Note 114
#define IDH_DISPATCH_Note 115
#define IDH_METHOD_Note_Show 116
#define IDH_METHOD_Note_Hide 117
#define IDH_PROPERTY_Note_IsChanged 118
#define IDH_METHOD_Note_Delete 119
#define IDH_PROPERTY_Note_Parent 120
#define IDH_PROPERTY_Note_NoteID 121
#define IDH_PROPERTY_Note_OnTop 122
#define IDH_PROPERTY_Note_Color 123
#define IDH_PROPERTY_Note_Left 124
#define IDH_PROPERTY_Note_Top 125
#define IDH_PROPERTY_Note_Height 126
#define IDH_PROPERTY_Note_Width 127
#define IDH_PROPERTY_Note_Text 128
#define IDH_PROPERTY_Note_Collapsed 129
#define IDH_PROPERTY_Note_IsVisible 130
#define IDH_PROPERTY_Note_Title 131
